CONTIKI_PROJECT = broadcasting_node
all: $(CONTIKI_PROJECT)

PLATFORMS_EXCLUDE = nrf52dk

MAKE_MAC = MAKE_MAC_TSCH
# MAKE_MAC = MAKE_MAC_CSMA
MAKE_NET = MAKE_NET_NULLNET

WERROR = 0

UIP_CONF_IPV6=0

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
